<a href="https://colab.research.google.com/github/FarhatMajidsofi/Python_Projects/blob/main/kfoldcv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
iris = load_iris()

In [44]:
from sklearn.model_selection import train_test_split
X_test, X_train, y_test, y_train = train_test_split(iris.data, iris.target, test_size=0.3)

In [45]:
logistic_reg = LogisticRegression(solver= 'liblinear', multi_class= 'ovr')
logistic_reg.fit(X_train,y_train)
logistic_reg.score(X_test, y_test)

0.8952380952380953

In [47]:
svm = SVC(gamma= 'auto')
svm.fit(X_train,y_train)
svm.score(X_test, y_test)

0.9904761904761905

In [49]:
random_forest = RandomForestClassifier(n_estimators=20)
random_forest.fit(X_train,y_train)
random_forest.score(X_test, y_test)

0.9714285714285714

In [24]:
from sklearn.model_selection import KFold
kfold =  KFold(n_splits = 3)
kfold

KFold(n_splits=3, random_state=None, shuffle=False)

In [28]:
for train_index, test_index in kfold.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
 print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [56]:
def get_score(model ,X_train,X_test,y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)


In [61]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits= 3)
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index,test_index in folds.split(iris.data,iris.target):
  X_train,X_test,y_train,y_test = iris.data[train_index],iris.data[test_index],iris.target[train_index], iris.target[test_index]
  scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),X_train, X_test, y_train, y_test))
  scores_svm.append(get_score(SVC(gamma = 'auto'),X_train, X_test, y_train, y_test))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators=20),X_train, X_test, y_train, y_test))


In [62]:
scores_logistic

[0.96, 0.96, 0.94]

In [63]:
scores_svm

[0.98, 0.98, 0.96]

In [65]:
scores_rf

[0.98, 0.94, 0.96]

In [66]:
from sklearn.model_selection import cross_val_score

In [70]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'),iris.data, iris.target,cv=3)

array([0.96, 0.96, 0.94])

In [73]:
cross_val_score(SVC(gamma = 'auto'),iris.data, iris.target,cv=3)

array([0.98, 0.98, 0.96])

In [76]:
cross_val_score(RandomForestClassifier(n_estimators=30) ,iris.data, iris.target,cv=3)

array([0.98, 0.92, 0.98])

In [78]:
scores1 = cross_val_score(SVC(C=5),iris.data,iris.target, cv=10)
np.average(scores1)

0.9800000000000001

In [83]:
scores2 = cross_val_score(SVC(C=20),iris.data,iris.target, cv=10)
np.average(scores2)

0.9733333333333334

In [84]:
scores3 = cross_val_score(SVC(C=40),iris.data,iris.target, cv=10)
np.average(scores3)

0.9666666666666668